<?php
$readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');
$writeConnection = Mage::getSingleton('core/resource')->getConnection('core_write');

$order = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId()); 

$token = $readConnection->fetchAll("SELECT token FROM `bloompa` WHERE `id_token`=1 LIMIT 0,1");
$token = $token[0]['token'];
if($token!='' && $token!='novo'):
?>
<!-- START - BLOOMP COMMERCE -->
<div id="bloompa-cart-widget"></div>
<?php if(isset($_SERVER["HTTPS"]) AND $_SERVER["HTTPS"] == "on"): ?>
<script src="https://www.bloompa.com.br/js/cart.widget-load.js" language="javascript" type="text/javascript"></script>
<?php else: ?>
<script src="http://www.bloompa.com.br/js/cart.widget-load.js" language="javascript" type="text/javascript"></script>
<?php endif;?>
<script language="javascript" type="text/javascript">
bcw.conversion({
token: "<?php echo $token?>",
order_id: "<?php echo $order->getId() ?>",
total_amount: "<?php echo $order->getGrandTotal() ?>"
});
</script>
<!-- END - BLOOMP COMMERCE -->
<?php endif; ?>