<?php 
$item = Mage::registry('product');

$readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');
$strsql = "SELECT * FROM `salesrule` WHERE `name`='Bloompa-Facebook' OR `name`='Bloompa-Twitter'";
$bloompa = $readConnection->fetchAll($strsql);
if(count($bloompa)>0):
	$strsql = "SELECT token FROM `bloompa` WHERE `id_token`=1 LIMIT 0,1";
	$token = $readConnection->fetchAll($strsql);
	$token = $token[0]['token'];
	if($token!=''&&$token!='novo'):
?>
<!-- START - BLOOMP COMMERCE -->
<div id="bloompa-product-widget"></div>
<script type="text/javascript">
var bcw_product = [{
prod_page_url: "<?=Mage::getBaseUrl().($item->_data['url_path']);?>",
prod_img_url: "<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product'.$item->_data['thumbnail'];?>",
prod_title: "<?=$item->_data['name'];?>",
prod_currency: "BRL",
prod_price: "<?=$item->_data['price'];?>"
}];

function loadBCW(){ bcw.init({token: "<?=$token;?>",product: bcw_product,show: true }); }

(function(){var bc = document.createElement("script"); bc.type = "text/javascript"; bc.async = true;bc.src = ("https:" == document.location.protocol ? "https://" : "http://") + "www.bloompa.com.br/js/product.widget-load.js";var s = document.getElementsByTagName("script")[0];s.parentNode.insertBefore(bc, s);bc.onload = loadBCW;})();
</script>
<!-- END - BLOOMP COMMERCE -->
<?php endif;
endif;
?>