<?php 
$readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');
$writeConnection = Mage::getSingleton('core/resource')->getConnection('core_write');
$coupon_code = Mage::getSingleton('checkout/session')->getQuote()->getCouponCode();

if(is_null($coupon_code)):	
	$token = $readConnection->fetchOne("SELECT value FROM `bloompa_settings` WHERE `param`='token' AND product='BloompCommerce' LIMIT 1");	
	if($token!='' && $token!='novo'):
?>

	<!-- BloompCommerce - cart -->
	<meta name="bloompa:source" content="cart" />
	<meta name="bloompa:cart-amount" content="<?php echo Mage::getSingleton('checkout/session')->getQuote()->getSubtotal(); ?>" />
	<!-- <meta name="bloompa:cart-discount_amount" content="4.00" /> -->
	<meta name="bloompa:cart-share_image" content="<?php echo $this->getLogoSrc()?>" />
	<meta name="bloompa:cart-redirect_url" content="<?php echo Mage::getBaseUrl().'bloompcommerce';?>" />
	<meta name="bloompa:cart-currency" content="BRL" />
	<meta name="bloompa:cart-show_banner" content="true" />	
	<!-- /BloompCommerce - cart -->

	<!-- BloompCommerce - Products in the shopping cart -->
	<?php foreach( Mage::getSingleton('checkout/session')->getQuote()->getItemsCollection() as $item ) : ?>
		<div data-prefix="bloompa:cart-product" data-title="<?php echo $item->_data['name'];?>" data-price="<?php echo $item->_data['price'];?>" data-url="<?php echo Mage::getBaseUrl().($item->_data['product']->_data['url_path']);?>" data-image="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product'.$item->_data['product']->_data['thumbnail'];?>" data-currency="BRL"></div>
	<?php endforeach; ?>
	<!-- BloompCommerce - Products in the shopping cart -->

	<!-- BloompCommerce - JS -->
	<script src="http<?php echo (isset($_SERVER["HTTPS"]) AND $_SERVER["HTTPS"] == "on")?'s':''?>://www.bloompa.com.br/js/bloompcommerce.widget-load.js" data-apitoken="<?php echo $token;?>"></script>
	<!-- /BloompCommerce - JS -->

	<?php endif;?>
<?php endif; ?>