<div id="bloompa-cart-widget" style="" ></div>
<?php 
$readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');
$writeConnection = Mage::getSingleton('core/resource')->getConnection('core_write');
$coupon_code = Mage::getSingleton('checkout/session')->getQuote()->getCouponCode();

if(is_null($coupon_code)):	
	$token = $readConnection->fetchOne("SELECT value FROM `bloompa_settings` WHERE `param`='token' AND product='BloompCommerce' LIMIT 1");	
	if($token!='' && $token!='novo'):
?>
	<script language="javascript" type="text/javascript">
		var bcw_products = [

		 // INÍCIO DO LOOP DE PRODUTOS	 
		 <?php foreach( Mage::getSingleton('checkout/session')->getQuote()->getItemsCollection() as $item ) : ?>
		 {	
		   prod_page_url: '<?php echo Mage::getBaseUrl().($item->_data['product']->_data['url_path']);?>', // REQUIRED VARIABLE
		   prod_img_url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product'.$item->_data['product']->_data['thumbnail'];?>', // REQUIRED VARIABLE
		   prod_title: '<?php echo $item->_data['name'];?>', // REQUIRED VARIABLE 
		   prod_price: '<?php echo $item->_data['price'];?>' // REQUIRED VARIABLE 	
		 },
		 <?php endforeach; ?>
		];
	</script>

	<script language="javascript" type="text/javascript" src="http<?php echo (isset($_SERVER["HTTPS"]) AND $_SERVER["HTTPS"] == "on")?'s':''?>://www.bloompa.com.br/js/cart.widget-load.js" rel="sbloompa-cart-widget"></script>
	
	<script language="javascript" type="text/javascript">
	bcw.init({
	    token: "<?php echo $token;?>",
	    cart_url:"<?php echo Mage::getBaseUrl().'bloompcommerce';?>",
	    store_logo: '<?php echo $this->getLogoSrc()?>',
			products_in_cart: bcw_products,
			cart_currency: 'BRL',
			cart_amount: '<?php echo Mage::getSingleton('checkout/session')->getQuote()->getSubtotal(); ?>'
	});
	</script>
	<?php endif;?>
<?php endif; ?>