<?php 
$readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');
$strsql = "SELECT * FROM `bloompa_settings` WHERE `param`='token' AND product='BloompCommerce' LIMIT 0,1";
$token = $readConnection->fetchAll($strsql);
$token = $token[0]['value'];	
if($token!='' && $token!='novo'):
?>
<!-- BloompCommerce - JS -->
<script src="http<?php echo (isset($_SERVER["HTTPS"]) AND $_SERVER["HTTPS"] == "on")?'s':''?>://www.bloompa.com.br/js/bloompcommerce.widget-load.js" data-apitoken="<?php echo $token;?>"></script>
<!-- /BloompCommerce - JS -->
<?php endif; ?>