<?php
$readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');
$writeConnection = Mage::getSingleton('core/resource')->getConnection('core_write');

$order = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId()); 

/*****************************
* START - Delete coupon code
*****************************/
@session_start();
$customer_id = $_SESSION['bc_customer_id'];
$social_network = $_SESSION['bc_social_network'];
unset($_SESSION['bc_customer_id']);
unset($_SESSION['bc_social_network']);
$model = Mage::getModel('salesrule/rule')
        ->getCollection()
        ->addFieldToFilter('name', array('eq'=>sprintf('AUTO_GENERATION CUSTOMER_'.$customer_id.' - '.intval($bc_discount_percent).'%% BloompCommerce-'.$social_network.' discount')))
        ->getFirstItem();
$model->delete();
/**********************
* END - Delete coupon code
**********************/


$token = $readConnection->fetchAll("SELECT * FROM `bloompa_settings` WHERE `param`='token' AND product='BloompCommerce' LIMIT 0,1");
$token = $token[0]['value'];
if($token!='' && $token!='novo'):
?>

	<!-- BloompCommerce - conversion -->
	<meta name="bloompa:source" content="conversion" />
	<meta name="bloompa:conversion-amount" content="<?php echo $order->getGrandTotal() ?>" />
	<meta name="bloompa:conversion-order_id" content="<?php echo $order->getId() ?>" />
	<meta name="bloompa:conversion-discount_amount" content="<?php echo $bc_discount_percent ?>" />
	<!-- /BloompCommerce - conversion -->

	<!-- BloompCommerce - JS -->
	<script src="http<?php echo (isset($_SERVER["HTTPS"]) AND $_SERVER["HTTPS"] == "on")?'s':''?>://www.bloompa.com.br/js/bloompcommerce.widget-load.js" data-apitoken="<?php echo $token;?>"></script>
	<!-- /BloompCommerce - JS -->

<?php endif; ?>